export const booksDatabase = [
  {
    title: "Emma",
    author: "Jane Austen",
    isbn: "9780007350780",
    price: 15,
    genre: ["fiction", "novel", "romance", "comedy"],
  },
  {
    title: "A Song of Ice and Fire",
    author: "George R.R. MArtin",
    isbn: "9780007477166",
    price: 65,
    genre: ["fantasy", "adventure", "set"],
  },
  {
    title: "The War of The Worlds",
    author: "H.G. Wells",
    isbn: "9780008190019",
    price: 10,
    genre: ["science", "fiction", "classics"],
  },
  {
    title: "The Poppy War",
    author: "R.F. Kuang",
    isbn: "9780008239848",
    price: 12,
    genre: ["fantasy"],
  },
  {
    title: "The Break Up",
    author: "Charlotte Barnes",
    isbn: "9780008511593",
    price: 9,
    genre: ["comedy", "romance"],
  },
  {
    title: "How To Stop Worrying And Start Living",
    author: "Dale Carnegie",
    isbn: "9780091906412",
    price: 11,
    genre: ["self_help"],
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    isbn: "9780141018829",
    price: 11,
    genre: ["philosophy"],
  },
  {
    title: "The Blind Watchmaker",
    author: "Richard Dawkins",
    isbn: "9780141026169",
    price: 17,
    genre: ["science"],
  },
  {
    title: "Unweaving The Rainbow",
    author: "Richard Dawkins",
    isbn: "9780141026183",
    price: 15,
    genre: ["science"],
  },
  {
    title: "The Hidden Oracle",
    author: "Rick Riordan",
    isbn: "9780141363929",
    price: 9,
    genre: ["adventure"],
  },
  {
    title: "Find Your Why",
    author: "Simon Sinek",
    isbn: "9780143111726",
    price: 11,
    genre: ["finance", "management"],
  },
  {
    title: "A History of the World",
    author: "Andrew Marr",
    isbn: "9780230764309",
    price: 20,
    genre: ["science"],
  },
  {
    title: "Circe",
    author: "Madeline Miller",
    isbn: "9780316423885",
    price: 10,
    genre: ["fiction"],
  },
  {
    title: "The Book Of Answers",
    author: "Carol Bolt",
    isbn: "9780316449915",
    price: 20,
    genre: ["science"],
  },
  {
    title: "To Kill A Mockingbird",
    author: "Harper Lee",
    isbn: "9780446310789",
    price: 9,
    genre: ["politics"],
  },
  {
    title: "Thinking For A Change",
    author: "John C. Maxwell",
    isbn: "9780446692885",
    price: 18,
    genre: ["managemnt", "religion"],
  },
  {
    title: "The Inheritance Games",
    author: "Jennifer Lynn Barnes",
    isbn: "9780759555402",
    price: 11,
    genre: ["thriller", "mystery"],
  },
  {
    title: "For One More Day",
    author: "Mitch Albom",
    isbn: "9780786891177",
    price: 12,
    genre: ["fiction"],
  },
  {
    title: "Fear",
    author: "Osho",
    isbn: "9781250006233",
    price: 16,
    genre: ["religion"],
  },
  {
    title: "Everything Guide To Borderline Personality Disorder",
    author: "Constance Dolecki",
    isbn: "9781440529702",
    price: 16,
    genre: ["self_help"],
  },
  {
    title: "Good Leaders Ask Great Questions",
    author: "John C. Maxwell",
    isbn: "9781455548095",
    price: 18,
    genre: ["managemnt"],
  },
  {
    title: "The 5 Levels Of Leadership",
    author: "John C. Maxwell",
    isbn: "9781546059813",
    price: 17,
    genre: ["management"],
  },
  {
    title: "The 15 Invaluable Laws Of Growth",
    author: "John C. Maxwell",
    isbn: "9781599953670",
    price: 18,
    genre: ["religion"],
  },
  {
    title: "Cashvertising",
    author: "Drew Eric Whitman",
    isbn: "9781601630322",
    price: 22,
    genre: ["marketing"],
  },
  {
    title: "Power",
    author: "Dennis Toombs",
    isbn: "9781633881914",
    price: 13,
    genre: ["self_help"],
  },
  {
    title: "The Times Of Our Lives",
    author: "Louise Hay",
    isbn: "9781788179768",
    price: 20,
    genre: ["self_help"],
  },
  {
    title: "Everything Youll Ever Need",
    author: "Charlotte Freeman",
    isbn: "9781949759259",
    price: 18,
    genre: ["self_help"],
  },
  {
    title: "Ceremony",
    author: "Brianna West",
    isbn: "9781949759334",
    price: 18,
    genre: ["self_help"],
  },
  {
    title: "When You're Ready This Is How You Heal",
    author: "Brianna Wiest",
    isbn: "9781949759440",
    price: 18,
    genre: ["self_help"],
  },
  {
    title: "YouRe Overthinking It",
    author: "Sabrina Alexis Bendory",
    isbn: "9781949759655",
    price: 18,
    genre: ["self_help"],
  },
  {
    title: "The Silent Thunderstorm",
    author: "Sarah Abou Chahine",
    isbn: "9789953058474",
    price: 10,
    genre: ["peotry"],
  },
  {
    title: "Losing Hope",
    author: "Colleen Hoover",
    isbn: "978147132810",
    price: 11,
    genre: ["romance"],
  },
  {
    title: "Think And Grow Rich",
    author: "Napoleon Hill",
    isbn: "9780091900212",
    price: 10,
    genre: ["self_help"],
  },
  {
    title: "Feel The Fear And Do It Anyway",
    author: "Susan Jeffers",
    isbn: "9780091917074",
    price: 13,
    genre: ["self_help"],
  },
  {
    title: "Bittersweet",
    author: "Susan Cain",
    isbn: "9780241300664",
    price: 22,
    genre: ["self_help", "psychology"],
  },
  {
    title: "This Is Marketing",
    author: "Seth Godin",
    isbn: "9780241370148",
    price: 22,
    genre: ["marketing"],
  },
  {
    title: "The Silva Mind Control Method",
    author: "Jose Silva",
    isbn: "9781982185886",
    price: 10,
    genre: ["psychology"],
  },
];

export const genres = [
  "fiction",
  "novel",
  "romance",
  "comedy",
  "fantasy",
  "adventure",
  "set",
  "classics",
  "self_help",
  "philosophy",
  "science",
  "adventure",
  "finance",
  "management",
  "politics",
  "religion",
  "thriller",
  "mystery",
  "marketing",
  "peotry",
  "psychology",
];
